### ISSUE TITLE
Improve MathML rendering in report

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#191] opened 2021-02-12 13:40 UTC
Formulas are currently not rendered very nicely in the SBML reports.
This uses currently Conent MathML to Presention MathML conversion via the MathJax XLS stylesheets. Unfortunately this does not work very well.
I added helper functions which allow to directly convert `ASTNode` to `Latex` in the `mathml.py`.
The report should be updated so that ASTNode, i.e. math is rendered as latex. 
This requires updating the math information in the report and using the latex string with addition `$${latex_str}$$` which can be rendered by MathJax. See the `mathml.html` for an example.

**Comment by sankha555** [comment] 2021-02-14 14:49
@matthiaskoenig I think I have understood what changes, but I am facing some problems in the tests.

My first attempt was to alter the ```math()``` method in ```sbmlreport.py``` in the following manner:
![image](https://user-images.githubusercontent.com/54751139/107879911-aa6f3f80-6f01-11eb-9051-759d2aa4bcb7.png)


However, this has been resulting in the following error in parsing the formula by sympy:
![image](https://user-images.githubusercontent.com/54751139/107879623-f4572600-6eff-11eb-8ce7-00b208d22b58.png)
A similar error has been raised in all 5 examples in ```test_report.py```.


I changed my approach a bit and converted astnode to string formula first and then used ```formula_to_latex()```. 
![image](https://user-images.githubusercontent.com/54751139/107879556-90346200-6eff-11eb-84b7-468e9772a50c.png)

This time, 4 out of the 5 examples passed, but the 3rd one throws a new error (please click on the image to enlarge them):
![image](https://user-images.githubusercontent.com/54751139/107879731-95de7780-6f00-11eb-8318-64682bc0b7c8.png)
![image](https://user-images.githubusercontent.com/54751139/107879739-a858b100-6f00-11eb-92de-ebda6e132588.png)
The above error seems to be thrown after the evaluation of ```_replace_piecewise()``` on the formula string. I have been trying to find the cause of the errors and methods to resolve them for the past couple of hours but haven't reached any suitable solution. 

Could you please help me in this regard and give me some pointers about how to approach resolving these errors? Also, if there is any other approach that I should have taken from the start of the issue, please provide me with some clues about that too. Thanks!

**Comment by matthiaskoenig** [comment] 2021-02-14 17:15
@sankha555 
A few things
- you should work on this repository and not on your fork so I can easily review the branches
- also make sure that you merge develop from time to time so your feature branch is up to date
- yes, you should update the `math` method, but without removing the old behavior, i.e. add an argument `type` which can be either `cmathml`, `pmathml` or `latex`. Depending on the flag you would create the different outputs. The setting should be based on an additional setting in the report function (`math_type`). Thereby it is possible to set what kind of math should be generated in the report. We will extend the SBML report settings soon, i.e., there will be additional options for customization.
- The `Symbol `dimensionless` is a bug in the mathml to sympy expression conversion in complex models with units; I can fix this when I have a branch with code I can commit to in this repository. You should use an example model which does not include such structures. I added the `repressilator` model which you can use with 
```
from sbmlutils.test import REPRESSILATOR_SBML
```
For now the other models are expected to fail until I add a fix for this.
We will add a test suite for the SBML report soon which will  allow to find more such bugs.

**Comment by sankha555** [comment] 2021-02-14 17:48
@matthiaskoenig Thanks a lot for the detailed explantation. I have been following the first two guidelines, and before working on a new issue I merge develop with the current version of the main repository. I am using the main repository for the work and make a new branch from updated develop for every new issue. I hope this workflow is suitable for our work. 

I will make a commit to the feature branch for this issue so that it would be convenient for you to track my work and also make any changes you would seem necessary for the bug fixes. I will make the first push right away and continue work on the points that you mentioned above in the commits that follow. I understand the issue in more detail now and hope to complete the patch better now. Thanks a lot!

**Comment by matthiaskoenig** [comment] 2021-02-14 19:32
@sankha555 Also don't put screenshots in the issue, but you can use the three backticks for error messages. I.e. just copy the output as a code block
```
This is a code block.
```
This makes it much easier to search for the error message.

**Comment by sankha555** [comment] 2021-02-14 19:41
Sure Sir, I would make sure to use this method to link error messages and console logs in the future messages now onwards.

**Closed** 2021-02-15 22:23 UTC
Labels: feature, report
